#!/bin/bash

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

sep="~"
s=$d$f0$sep$t

kernel="$(uname -r | cut -d '-' -f1)"

shell=$(basename $SHELL)

# (\ /)
# ( . .) ( · ·)
# c(")(")

cat << EOF

(\ /)$f4    sh  $t$sep $shell
( $d. .$t)$f4   kr  $t$sep $kernel
c($f1"$t)($f1"$t)$f4  mem $t$sep $(free -h | grep Mem | awk '{print $3}') / $(free -h | grep Mem | awk '{print $2}')

EOF
